### ISSUE TITLE
Using this library breaks styled components

### ISSUE THREAD

**Issue by JoaoTMDias** [cedricdelpoux/react-svg-line-chart#11]
I'm using styled components with my project and I was trying to include this library (react-svg-line-chart) in my project, but it breaks the current styled components I have in my project. 

Is there anyway to circumvent this? Thanks?
I'm using create-react-app, by the way.

**Comment by cedricdelpoux** [comment]
What do you mean by "it breaks the current styled components" ?

**Comment by JoaoTMDias** [comment]
Sorry, my message was a bit vague, I agree.
So, just to clarify: i'm using styled components to style parts of my app. They work fine.

But if I call your library inside a component ( ex: import LineChart from 'react-svg-line-chart'), they no longer compile. No error is thrown in the console, but I noticed something was wrong because some (not all) of my styles were not being shown.

The moment I removed that import, everything was working as usual. Which is a bit strange, I know, but I just wanted to let you know! :)

**Comment by cedricdelpoux** [comment]
Ok thank you for your feedback, it's very strange you are the first give me this issue since the v2.0 is out (November 2017). 
Maybe it's an incompatibility problem between multiple `styled-components` version. What version do you use in your project ?

**Comment by JoaoTMDias** [comment]
Hang on, now it worked!:)
I updated node from 9.8.0 to 9.11.1, and it also updated my styled-components from 3.1.6 to 3.2.5.
So it must have been related with my own version of styled-components.

Anyway, I'm using  your demo to show the chart on the screen, and whenever I click on it, it throws this error: "TypeError: activePoint is null"
