### ISSUE TITLE
Tooltip support

### ISSUE THREAD

**Issue by pietrofxq** [cedricdelpoux/react-svg-line-chart#14]
is it possible to add a tooltip for each point in the chart?

**Comment by cedricdelpoux** [comment]
Hi @pietrofxq, 

I just added an example in the demo code.
You can see code here: https://github.com/xuopled/react-svg-line-chart/blob/master/demo/src/tooltips.js
You can see a live demo here: http://xuopled.github.io/react-svg-line-chart/tooltip
