### ISSUE TITLE
Compress/Offset Axis

### ISSUE THREAD

**Issue by SaltySousChef** [cedricdelpoux/react-svg-line-chart#16]
Is it possible to better display information by only showing the range of data (i.e starting the axis at a number other than 0)

![screenshot 2018-12-18 at 19 19 25](https://user-images.githubusercontent.com/30601942/50177423-e266a200-02f9-11e9-9f9a-1c44d8a4cd5e.png)

My data set is all in the thousands so my chart is almost all white space.

**Comment by cedricdelpoux** [comment]
Hi @hosekhoshtaghaza, at this moment it is not possible to do what you want to do. But feel free to open a PR and help me improve this lib :)
