### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by wxqGitHub** [cedricdelpoux/react-svg-line-chart#3]
hi : 
    I used the code in Example, but  it have error,  like this 

```
index.js?0608:1 Uncaught TypeError: Cannot call a class as a function
```

so. How to fix

**Comment by truenorthcreative** [comment]
In index.js (or the root you're including it) -- the class needs to extend React.Component {

```
export default class LineChart extends React.Component {
```

**Comment by peterholmberg** [comment]
I'm also getting this error. Don't really understand your solution @truenorthcreative

**Comment by cedricdelpoux** [comment]
I will take a look the next week

**Comment by cedricdelpoux** [comment]
It should be ok now
