### ISSUE TITLE
Freeze if all y coords = 0

### ISSUE THREAD

**Issue by pustovav** [cedricdelpoux/react-svg-line-chart#5]
Hi. I used your code (I have changed it a little bit) in my react type script application.
 When I pass data where all y coords are 0 browser just freezes.
I figured out that the problem is in getMaxY function

``` javascript
getMaxY() {
    const { data, yLabelsNb } = this.props
    const maxY = data.length > 0 ? data.reduce((max, point) => point.y > max ? point.y : max, data[0].y) : 0
    return Math.ceil(maxY / yLabelsNb) * yLabelsNb
  }
```

So I have solve the problem the following way:

``` javascript
getMaxY() {
    const { data, yLabelsNb } = this.props;
    const maxY = data.length > 0 ? data.reduce((max, point) => point.y > max ? point.y : max, data[0].y) : 0;
    return maxY ? Math.ceil(maxY / yLabelsNb) * yLabelsNb : yLabelsNb;
  }
```

I hope this issue wasn't caused by my changes.

**Comment by cedricdelpoux** [comment]
Thank you very much. I published this fix in 1.0.5
